//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AzureAccount
    {
        public AzureAccount()
        {
            this.Powerbis = new HashSet<Powerbi>();
        }
    
        public int AccountId { get; set; }
        public string ClientId { get; set; }
        public string ClientSecret { get; set; }
        public string TenantId { get; set; }
        public string User { get; set; }
        public byte[] Password { get; set; }
        public string AccessToken { get; set; }
        public Nullable<System.DateTime> ExpiresOn { get; set; }
        public string RefreshToken { get; set; }
        public string IdToken { get; set; }
        public AzureResources Resource { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Powerbi> Powerbis { get; set; }
    }
}
