//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    
    public enum DisplayAutoLoadModes : int
    {
        DisplayAutoLoadMode_IP = 0,
        DisplayAutoLoadMode_Cookie = 1
    }
}
