//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeAccount
    {
        public ExchangeAccount()
        {
            this.Outlooks = new HashSet<Outlook>();
        }
    
        public int AccountId { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public byte[] Password { get; set; }
        public OutlookEwsVersions EwsVersion { get; set; }
        public string Url { get; set; }
    
        public virtual ICollection<Outlook> Outlooks { get; set; }
    }
}
