//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frame
    {
        public Frame()
        {
            this.Locations = new HashSet<Location>();
        }
    
        public int FrameId { get; set; }
        public int PanelId { get; set; }
        public int Duration { get; set; }
        public Nullable<System.DateTime> BeginsOn { get; set; }
        public Nullable<System.DateTime> EndsOn { get; set; }
        public Nullable<int> Sort { get; set; }
        public System.DateTime DateCreated { get; protected set; }
    
        public virtual Clock Clock { get; set; }
        public virtual Panel Panel { get; set; }
        public virtual Memo Memo { get; set; }
        public virtual News News { get; set; }
        public virtual Picture Picture { get; set; }
        public virtual Report Report { get; set; }
        public virtual Video Video { get; set; }
        public virtual Weather Weather { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual Html Html { get; set; }
    }
}
