//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullScreen
    {
        public int PanelId { get; set; }
        public int CanvasId { get; set; }
        public Nullable<int> MaxIdleInterval { get; set; }
    
        public virtual Canvas Canvas { get; set; }
        public virtual Panel Panel { get; set; }
    }
}
