//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OauthAccount
    {
        public OauthAccount()
        {
            this.Weathers = new HashSet<Weather>();
        }
    
        public int AccountId { get; set; }
        public OauthProviders Provider { get; set; }
        public string Name { get; set; }
        public string AppId { get; set; }
        public string ClientId { get; set; }
        public string ClientSecret { get; set; }
    
        public virtual ICollection<Weather> Weathers { get; set; }
    }
}
