//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outlook
    {
        public int FrameId { get; set; }
        public OutlookModes Mode { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public byte[] Password { get; set; }
        public string Mailbox { get; set; }
        public OutlookEwsVersions EwsVersion { get; set; }
        public string Url { get; set; }
        public int ShowEvents { get; set; }
    
        public virtual Frame Frame { get; set; }
    }
}
