//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    
    public enum OutlookEwsVersions : int
    {
        OutlookEwsVersion_Exchange2007_SP1 = 0,
        OutlookEwsVersion_Exchange2010 = 1,
        OutlookEwsVersion_Exchange2010_SP1 = 2,
        OutlookEwsVersion_Exchange2010_SP2 = 3,
        OutlookEwsVersion_Exchange2013 = 4,
        OutlookEwsVersion_Exchange2013_SP1 = 5
    }
}
