//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    
    public enum OutlookPrivacy : int
    {
        OutlookPrivacy_All = 0,
        OutlookPrivacy_NoClassified = 1,
        OutlookPrivacy_ProtectSubject = 2
    }
}
