//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Powerbi : Frame
    {
        public int AccountId { get; set; }
        public Nullable<PowerbiTypes> Type { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public Nullable<System.Guid> DashboardGuid { get; set; }
        public Nullable<System.Guid> TileGuid { get; set; }
        public Nullable<System.Guid> ReportGuid { get; set; }
        public Nullable<System.Guid> GroupGuid { get; set; }
    
        public virtual AzureAccount AzureAccount { get; set; }
    }
}
