//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Powerbi
    {
        public int FrameId { get; set; }
        public int AccountId { get; set; }
        public PowerbiTypes Type { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
    
        public virtual AzureAccount AzureAccount { get; set; }
        public virtual Frame Frame { get; set; }
    }
}
