//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    
    public enum RenderModes : int
    {
        RenderMode_Crop = 0,
        RenderMode_Stretch = 1,
        RenderMode_Fit = 2,
        RenderMode_Fill = 3
    }
}
