//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportServer
    {
        public ReportServer()
        {
            this.Reports = new HashSet<Report>();
        }
    
        public int ServerId { get; set; }
        public string BaseUrl { get; set; }
        public string User { get; set; }
        public byte[] Password { get; set; }
        public string Domain { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Report> Reports { get; set; }
    }
}
