//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    
    public enum SettingTypes : int
    {
        SettingType_IntPositive = 0,
        SettingType_String = 1,
        SettingType_DecimalPositive = 2,
        SettingType_Int = 3,
        SettingType_Decimal = 4,
        SettingType_Binary = 5
    }
}
