//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Youtube : Frame
    {
        public string Name { get; set; }
        public string YoutubeId { get; set; }
        public int Volume { get; set; }
        public bool AutoLoop { get; set; }
        public YTAspect Aspect { get; set; }
        public YTQuality Quality { get; set; }
        public int Start { get; set; }
        public YTRate Rate { get; set; }
    }
}
