//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    
    public enum YTAspect : int
    {
        YTAspect_Auto = 0,
        YTAspect_16x9 = 1,
        YTAspect_4x3 = 2
    }
}
