//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    
    public enum YTQuality : int
    {
        YTQuality_Default = 0,
        YTQuality_Small = 1,
        YTQuality_Medium = 2,
        YTQuality_Large = 3,
        YTQuality_Hd720 = 4,
        YTQuality_Hd1080 = 5,
        YTQuality_HiRes = 6
    }
}
