//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    
    public enum YTRate : int
    {
        YTRate_Normal = 0,
        YTRate_VerySlow = 1,
        YTRate_Slow = 2,
        YTRate_Fast = 3,
        YTRate_VeryFast = 4
    }
}
